---
date: 2019-12-18
params:
  transkript: NA
title: Persönlicher Einblick - WINTERPAUSE des Welpen und Junghunde
  Podcasts bis 8.1.2020
toc-title: Table of contents
---

 Hallo ihr Lieben, leider keine richtige Podcastfolge heute, sondern ein kleiner Einblick in mein Privatleben bzw. in den Ausblick der nächsten Podcast Episode und der letzten. Ich wollte erklären, warum es in letzter Zeit nicht so häufig vorgekommen ist, sich eine Podcastfolge aufgenommener Arbeit und das ist eine Podcast Pause gebenbild bis 8. Jänner, also der Mittwoch in der zweiten Jänner Woche. Das ist da unbedingt wieder dabei sein, bis dahin will das keine weitere Folge geben. Warum ist das so? Hauptsächlich liegt es ganze an meiner Masterarbeit. Denn ich wollte eigentlich schon viel früher fertig sein, dass wir geplant gewesen, eigentlich im Sommer. Ja jetzt ist es Dezember und ich bin immer noch nicht fertig. Aber ich hoffe, dass ich in den nächsten zwei Tagen abgeben kann. Also heute ist da Moment der ist der 18. und ich hätte gerne das vor den 20. abgeben wird, das heißt, ich hoffe, ich schaffte es. Ich bin da aber jetzt mal guter Dinge. Vielleicht kurz zu meiner Masterarbeit, weil ich war viele Fragen bekommen habe. Es geht dabei um Welpen und zwar um Stress-Risilians erhöhen. Wenn man also ich habe einen Zeitraum von der dritten bis zu sechsten Lebenswoche untersucht, die Welpen in der Zeit trainiert und mit ihnen viele Übungen gemacht. Und dann geschaut, was das für einen Effekt auf ihr Verhalten auf bestimmte Reize bzw. Übungen hat. Leider kann ich noch keine Details zu den Ergebnissen sagen. Ich kann das sagen, dass ja, dass ich total begeistert bin, von dem, was Herr Rask gekommen ist, nur bevor man mit Ergebnissen umsichwirft, muss man das zuerst in einem Journal einreichen bzw. auch dem Professor zeigen. Also ich habe das her jetzt noch nicht abgeschickt und auch noch nicht veröffentlicht und deswegen kann ich jetzt auch noch nicht groß herausbrussauen, was dabei herausgekommen ist. Aber ich werde das sicher dann machen, wenn es so weit ist und wenn alles dann endlich mal abgeschlossen ist. Nur kurz zu der Entstehung von so einer Studie, also das ist sehr groß angelegt gewesen. Meine, ich habe tatsächlich jetzt zwei Jahre an der Studie gearbeitet, er kann alleine. Ich hatte eine Betrohrend, die aber in der Schweiz lebt und wir hatten im Kontakt, weil ich habe im Prinzip alles alleine gemacht und bin von einem Züchter zum anderen gefahren und habe insgesamt 30 Welben trainiert und getestet. Ich denke aber bevor ich jetzt mich da in Details verliere, werde ich eine eigene Podcastfolge dazu machen, um was es genau gegangen ist, was ich genau gemacht habe und was auch genau die Ergebnisse sind oder waren, wenn euch das interessiert. Ich denke, ich denke, dass ein Welpen Podcast ist, passt das sehr ganz gut. Gut, also das ist da Hauptgrund, es hat jetzt in der Zeit nicht zu viele Podcastfolgen gekommen sind. An weiterer Grund ist das gerade auf Instagram, also wenn du mir da noch Instagram oder Instagram ich weiß nicht, wie ich das Aussprechen soll. Egal, dass wenn du mir dort folgst, dann hast du das bestimmt mitbekommen, dass wir gerade eine advanced-kalen der Aktion haben, wo ich mit ganz vielen anderen tollen Menschen Videos, Gifstalte und Wissen, Preisgebe für also jeden Tag für Welpen und junge bisitze und das auch recht viel Arbeit ist und erlieb, da rein steckt und deshalb die Podcastfolgen sind ein bisschen kürzer dritten. Wenn du also in Putemörchtest, dann schauen, ob ich den dort vorbei. Ich habe das auch in den Hallets abgespeichert, das heißt man kann sich die vergangenen Tage und Videos immer noch ansehen. Ich habe da zum Beispiel hier gezeigt mit Mila wie man Putemörnieren aufbaut und wie man dem Hund beibringen kann, dass er eine Weihnachtsmütze trägt, es kommt dann heute noch Tipps und Tricks zu Familienfesten mit Hund. Also wenn du deinen Welpen bei den ganzen Familienfesten mitnehmen willst, was du dabei achten kannst und was noch genau und Silvester Tipps werden auch noch kommen. Und auch von meinen Kolleginnen und Kollegen kommen auch noch ganz tolles Sachen. Das heißt bitte dort unbedingt rein schon bzw. sind schon gekommen, mit ganz viel mehr Wert zu Bewegung, wie viel darf sich in Hund bewegen, ein junghund. Also bitte unbedingt weiß ihr noch kein Instagram habt. Dann installiert es euch ein, genau, da ist es auch einfach weil da kann ich viel in Videos und Bild zeigen, als hier in Putemörn. Ja und der dritte Punkt sind natürlich meine Training, meine Kunden, ich liebe See und ich will mich auch um sie kümmern und deswegen stehen die anderen Sachen natürlich hinten an, weil das hat für mich totale Priorität. Und das waren so die Gründe, das haben das jetzt ein bisschen sporadisch nur kam, das war diese neuen Podcast voll. Ja ein kurzer Ausblick vielleicht in Sja 2020, ich werde oder ich planet nachdem dann hoffentlich irgendwann mein Master abgeschlossen ist. Also neben der Masterbeit, die ich ja jetzt hoffentlich bald abschicker, wird die dann auch noch publiziert. Das ist ein langen schwieriger Prozess in der Wissenschaft das einzurreichen und dann vielleicht nochmal zu korrigieren oder was auch immer. Ich weiß noch nicht genau, was da auf mich zukommt. Jedenfalls neben der fehlt mir dann noch eine Prüfung und dann natürlich dann die Defensio. Wenn dann dieser am Brocken mal erledigt ist und ich studiere dafür jetzt schon echt ewig, das ist mir fast unangenehm zu sagen, aber hilft der nächste ist es halt, ich arbeite ja nebenbei. Also wenn der Brocken dann mal erledigt ist, dann kann ich mich voll und ganz dem Thema Weltman-Jung und der Wittmann und das ist dann wirklich perfekt und ich frem ich hier riesig da drauf. Vielleicht ganz kurz zu was ich überhaupt studiere, falls du das nicht weißt ist für halten es Neuro und Konkognitionsbiologie und ich hatte eben das große große große große Glück, meine eigene Studie zu machen und das mit welpen was einfach perfekt so meinem Thema passt. Gut, als er ausblick für 2020 war es die Podcast folgen betrifft schanzeiert. Sehr gut aus, ich werde jetzt eine Pause noch machen bis achten jener, das heißt dann unbedingt am Startsam, vor allem wenn bei dir in den Winterferien jetzt ein Welpe anzieht und bis dahin kannst du super super gerne auf Instagram vorbeigean, da werde ich regelmäßig am bald bleiben und in wo es lief an und hoffe das er das nicht, dass neben meinem Schi Urlaub gut ausgeht aber ich bin guter Dinge. Ja, warte es möchte ich mich gerne bedanken für die zahlreichen höhere und höhere Gennem von diesem Podcast, es hat sich so viel getan und ich bin so unglaublich glücklich dass das so viele Menschen diesen Podcast her und ich würde mich also wende mir ein riesengeschänk machen möchte, das würde ich mich so freuen also natürlich nur wenn dir der Podcast geholfen hat oder hilft und wenn wenn er dir gefällt dass du mir eine bewertung gibt bzw. in abonniert weil das ich werde dann einfach das andere drauf stoßen und das würde mich unglaublich freuen wenn du dir die Zeit nehmen würdest den Podcast end wie der zu bewerten oder auf Facebook eine bewertung zu schreiben oder auf Google oder was ich immer oder auf eben Apple Podcast und falls da nicht weißt wie du das machen kannst und würde mich auch so auf freuen wenn du mich fragst und genau also das würde mir total helfen und mich mich im mega mega riesig riesig riesig freuen. Ja was die Themen für folgen 2020 betreffen wenn du wünschehaß bitte schreiben dir super gerne ich plane ich habe große Pläne also ich plane interviewes ich plane ich habe so viele Themen über die ich noch sprechen möchte verandert für dich auch was was gewissenschafts sagt und natürlich auch meine studie und ganz viele treningste teamen und ja unglaublich viele Pläne habe ich ich hoffe ich habe auch die Zeit dafür aber ja er werde sehen. In dem Sinne freue ich mich auf ein wieder hören im am 8. Janah bzw. dann im Jahr 2020 ich wünsche euch hier schon mal ein möglichst entspanntes fest und ein möglichst entspannte Weihnachtszeit mit eurem Welken oder jungen wenn du dazu tips brauchst beim scharfe bei auf Instagram und ja ich wünsche dir alles alles liebe herzlichem dank dass du meinen Podcast herst und rutscht in jedem bald gut rüber insenten und ja ich sag jetzt Tschüss!